[theme]
# Primary accent color for interactive elements.
primaryColor = "#631284"

# Background color for the main content area.
backgroundColor = "#000548" 

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#123284"

# Color used for almost all text.
textColor = "#DDD"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"